In [9]:
from PIL import Image
import numpy as np

im_frame = Image.open('./' + 'this1small.png')
np_frame = np.array(im_frame.getdata())
# img = Image.fromarray(np_frame) 
# img.save('dummy.png')
#extracting RGB elements
R=[]
G=[]
B=[]

for i in range(len(np_frame)):
    R.append(np_frame[i][0])
    G.append(np_frame[i][1])
    B.append(np_frame[i][2])
    
#converting first 9 into binary
for i in range(9):
    R[i]=format(np_frame[i][0],'08b')
    G[i]=format(np_frame[i][1],'08b')
    B[i]=format(np_frame[i][2],'08b')


#creating LSB matrix 3*9
LSB = [[0 for x in range(9)] for y in range(3)] 
for i in range(9):
    LSB[0][i]=R[i][7]
for i in range(9):
    LSB[1][i]=G[i][7]
for i in range(9):
    LSB[2][i]=B[i][7]


#embedding secret inside LSB
secret="110111111101010000100001101"
k=0
for x in range(0,3):
    for y in range(0,9):
        LSB[x][y]=secret[k]
        k+=1

#putting embedded LSBs into RGB arrays on first 9 index
i=0
for x in range(0,9):
    R[x]=R[x][0:7]+LSB[0][i]
    G[x]=G[x][0:7]+LSB[1][i]
    B[x]=R[x][0:7]+LSB[2][i]
    i+=1
    
#converting arrays from binary to decimal
for x in range(0,9):
    R[x]=int(R[x],2)
    G[x]=int(G[x],2)
    B[x]=int(B[x],2)
    
#appending values from np_frame to make mini arrays to bigger ones
# for x in range(9,len(np_frame)):
#     R.append(np_frame[x][0])
#     G.append(np_frame[x][1])
#     B.append(np_frame[x][2])

#creating final np_frame
for i in range(9):
    np_frame[i][0]=R[i]
    np_frame[i][1]=G[i]
    np_frame[i][2]=B[i]

arr1 = np_frame.reshape(25, 25,-1)
print("---------")
print(arr1)
im = Image.fromarray(arr1)
im.save('dummy22.png')



# rgbArray = np.zeros((len(np_frame),len(np_frame),3), 'uint8')
# for i in range(len(np_frame)):
#     rgbArray[i][0]=R[i]*255
#     rgbArray[i][1]=G[i]*255
#     rgbArray[i][2]=B[i]*255
# # rgbArray[..., 0] = R
# # rgbArray[..., 1] = G
# # rgbArray[..., 2] = B
# img = Image.fromarray(rgbArray,mode="RGB") 
# img.save('myimg1.png')

print("complete")

---------
[[[207 209 207]
  [183 186 182]
  [168 173 168]
  ...
  [ 71 167 173]
  [ 60 173 183]
  [ 47 184 201]]

 [[186 189 202]
  [173 177 198]
  [169 171 193]
  ...
  [ 38 170 178]
  [ 53 171 180]
  [ 58 176 189]]

 [[166 176 186]
  [161 172 188]
  [172 172 185]
  ...
  [ 11 176 186]
  [ 28 173 182]
  [ 68 172 182]]

 ...

 [[106 161 108]
  [ 85 170  87]
  [ 98 187  60]
  ...
  [198   8 156]
  [223   2 159]
  [208   7 154]]

 [[ 92 130 142]
  [ 77 142 134]
  [ 91 175  80]
  ...
  [189   1 147]
  [206   5 149]
  [173  26 146]]

 [[ 72 104 148]
  [ 61 109 133]
  [ 63 133  93]
  ...
  [155  23 142]
  [180  19 144]
  [176  27 147]]]


TypeError: Cannot handle this data type: (1, 1, 3), <i4